inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - db/**/*
    - script/**/*
    - vendor/**/*
    - bin/**/*

Rails:
  Enabled: true

Documentation:
  Enabled: false

MethodLength:
  Severity: warning
  Max: 15

Style/AndOr:
  Enabled: false

Metrics/LineLength:
  Max: 180

GuardClause:
  MinBodyLength: 3

Style/Lambda:
  Exclude:
      - config/**/*
