dist: focal
sudo: false
language: ruby
cache:
  bundler: true
  directories:
    - node_modules
  yarn: true
services:
  - redis-server
addons:
  - postgresql: "13"
before_install:
  - gem install bundler -v 2.2.28
  - yarn --ignore-engines
  - bundle config gems.contribsys.com $COVERALLS_REPO_TOKEN
bundler_args: --without production doc
before_script:
  - bundle exec rails db:setup RAILS_ENV=test
env:
  - REDIS_PORT_6379_TCP_ADDR=localhost REDIS_PORT_6379_TCP_PORT=6379 REDIS_PORT_6379_TCP_ADDR_SESSION=localhost REDIS_PORT_6379_TCP_PORT_SESSION=6379 TRAVIS=true GIVE_SESSION_KEY=99999
script:
  - bundle exec standardrb
  - bundle exec bundle audit check --update --ignore CVE-2015-9284
  - bundle exec brakeman -A -q --no-pager --ensure-latest
